### ISSUE TITLE
Possible issue with login

### ISSUE THREAD

**Issue by jonte964** [sindrebroch/ha-flexit#4]
I have 2.0.1 (thanks for the key resolution) and HA 2021.8.7.

I have verified internet connectivity in the FlexIT Go app and can enter both on the same LAN as well as over mobile with my IOS app.

When adding the same username (email) and password as in the Go app I get "connection failed".

Reinstall attempted via Hacs and password for Go app changed to verify it has been correct.

Any insight would be helpful.

(Thanks for your work!)

**Comment by sindrebroch** [comment]
I dont have any immediate ideas, but I would love to figure it out. 

Are there any logs showing up? You can try turning on debug-logging to see if anything shows up.
In configuration.yml:
```
logger:
  default: info
  logs:
    custom_components.flexit.__init__: debug
    custom_components.flexit.config_flow: debug
```

Which Flexit unit do you have? 

Is "Failed to connect" the error-message or "connection failed"?

Its either when trying to authenticate or when its trying to fetch available units from the cloud. Might need some error-handling.
